[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scraperlib"
version = "0.0.1"
description = "A Python library for web scraping"
authors = [{ name = "IQLynxAI", email = "iqlynx.ai@gmail.com" }]
dependencies = ["selectolax", "curl_cffi"]
