name: Upload Python Package

on:
  # Trigger the workflow on any tag push
  push:
    tags:
      - "*"  # Matches any tag

permissions:
  contents: read  # Required to read repository contents
  id-token: write # Required for trusted publishing with OIDC

jobs:
  deploy:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Uses the latest Python 3 version

      # Step 3: Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Step 4: Build the Python package
      - name: Build package
        run: python -m build

      # Step 5: Publish the package to PyPI using trusted publishing
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1